# Generated by Django 6.0.7 on 2026-07-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_count', models.PositiveIntegerField(default=6, verbose_name='ظرفیت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
            ],
            options={
                'verbose_name': 'ظرفیت پلن',
                'verbose_name_plural': 'ظرفیت پلن',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('amount', models.CharField(max_length=50, verbose_name='مبلغ واریزی')),
                ('receipt', models.ImageField(upload_to='receipts/', verbose_name='رسید پرداخت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('approved', 'تایید شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
            ],
            options={
                'verbose_name': 'ثبت نام پلن',
                'verbose_name_plural': 'ثبت نام\u200cها',
            },
        ),
    ]
