# Generated by Django 6.0.7 on 2026-07-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveIntegerField(default=10, verbose_name='ظرفیت')),
                ('is_open', models.BooleanField(default=True, verbose_name='ثبت\u200cنام فعال باشد؟')),
                ('closed_message', models.CharField(default='ظرفیت این دوره تکمیل شده است.', max_length=200, verbose_name='پیام تکمیل ظرفیت')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Capacity',
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={},
        ),
        migrations.RemoveField(
            model_name='submission',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='name',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='status',
        ),
        migrations.AddField(
            model_name='submission',
            name='full_name',
            field=models.CharField(default=1, max_length=80, verbose_name='نام و نام خانوادگی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='note',
            field=models.CharField(blank=True, max_length=300, verbose_name='توضیحات (اختیاری)'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='receipt',
            field=models.ImageField(upload_to='receipts/', verbose_name='عکس رسید'),
        ),
    ]
