# Generated by Django 6.0.7 on 2026-07-19 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vip', '0002_siteconfig_delete_capacity_alter_submission_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteconfig',
            options={'verbose_name': 'تنظیمات سایت', 'verbose_name_plural': 'تنظیمات سایت'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-created_at'], 'verbose_name': 'ارسال اطلاعات', 'verbose_name_plural': 'ارسال\u200cهای کاربران'},
        ),
    ]
