# Generated by Django 6.0.7 on 2026-07-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip', '0003_alter_siteconfig_options_alter_submission_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='note',
        ),
        migrations.AddField(
            model_name='submission',
            name='national_id',
            field=models.CharField(default=1, max_length=20, verbose_name='کد ملی'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='closed_message',
            field=models.CharField(default='ظرفیت این پلن تکمیل شده است.', max_length=200, verbose_name='پیام تکمیل ظرفیت'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت'),
        ),
    ]
