# Generated by Django 6.0.7 on 2026-07-25 07:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip', '0004_remove_submission_note_submission_national_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='توکن')),
                ('minutes', models.PositiveIntegerField(default=20, verbose_name='اعتبار (دقیقه)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان انقضا')),
                ('is_used', models.BooleanField(default=False, verbose_name='استفاده شده؟')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان استفاده')),
            ],
            options={
                'verbose_name': 'لینک اختصاصی',
                'verbose_name_plural': 'لینک\u200cهای اختصاصی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='default_link_minutes',
            field=models.PositiveIntegerField(default=20, verbose_name='اعتبار پیش\u200cفرض لینک (دقیقه)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='instagram_url',
            field=models.URLField(default='https://www.instagram.com/mohamadfereidouny?igsh=dHFmNnVmZzdwbHA=', max_length=300, verbose_name='لینک اینستاگرام'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='telegram_id',
            field=models.CharField(default='Mohamadfereidouny', max_length=60, verbose_name='آیدی تلگرام محمد فریدونی'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='telegram_shooter_vip',
            field=models.CharField(default='SHOOTER_VIP', max_length=60, verbose_name='آیدی تلگرام SHOOTER_VIP'),
        ),
        migrations.AddField(
            model_name='submission',
            name='invite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vip.invitelink', verbose_name='لینک اختصاصی'),
        ),
    ]
